[tool.pdm]

[project]
name = ""
version = ""
description = ""
authors = [
    {name = "vsedov", email = "viv.sedov@hotmail.com"},
]
dependencies = [
    "matplotlib>=3.7.0",
    "numpy>=1.24.2",
    "scipy>=1.9.3",
]
requires-python = ">=3.10"
license = {text = "MIT"}
